org: amvijay.com
app: lambda-function-file-splitter
service: file-splitter

provider:
  name: aws
  stage: dev
  region: us-west-2
  runtime: java17

package: 
  artifact: target/s3-large-file-splitter-1.0.0.jar

functions:
  file-splitter: 
    handler: com.amvijay.aws_learning.lambda.s3_large_file_splitter.Handler
    name: file-splitter
    
  
